import '../models/course.dart';

final realCourses = [
  Course(
    id: '11024295-001', name: '컴퓨터공학을위한수학Ⅰ', professor: '최상민',
    credit: 3, rating: 3.2, difficulty: 4,
    hasTeamProject: false, isMajorRequired: true, grade: 1,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024295-002', name: '컴퓨터공학을위한수학Ⅰ', professor: '최상민',
    credit: 3, rating: 3.2, difficulty: 4,
    hasTeamProject: false, isMajorRequired: true, grade: 1,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024725-001', name: 'C프로그래밍', professor: '김창근',
    credit: 3, rating: 4, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 1,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024725-002', name: 'C프로그래밍', professor: '김창근',
    credit: 3, rating: 4, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 1,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024725-003', name: 'C프로그래밍', professor: '윤웅창',
    credit: 3, rating: 4, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 1,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024725-004', name: 'C프로그래밍', professor: '윤웅창',
    credit: 3, rating: 4, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 1,
    timeSlots: [TimeSlot(day: '목', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024294-001', name: '컴퓨터공학을위한수학Ⅱ', professor: '서현',
    credit: 3, rating: 3, difficulty: 4,
    hasTeamProject: false, isMajorRequired: true, grade: 2,
    timeSlots: [TimeSlot(day: '목', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024294-002', name: '컴퓨터공학을위한수학Ⅱ', professor: '서현',
    credit: 3, rating: 3, difficulty: 4,
    hasTeamProject: false, isMajorRequired: true, grade: 2,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11009499-001', name: '컴퓨터시스템개론', professor: '이로빈',
    credit: 3, rating: 3.5, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '월', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11009499-002', name: '컴퓨터시스템개론', professor: '이로빈',
    credit: 3, rating: 3.5, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '월', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11009499-003', name: '컴퓨터시스템개론', professor: '이로빈',
    credit: 3, rating: 3.5, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024300-001', name: 'C++프로그래밍', professor: '김흥준',
    credit: 3, rating: 3.8, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024300-002', name: 'C++프로그래밍', professor: '김흥준',
    credit: 3, rating: 3.8, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024300-003', name: 'C++프로그래밍', professor: '김흥준',
    credit: 3, rating: 3.8, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '월', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024300-004', name: 'C++프로그래밍', professor: '이수원',
    credit: 3, rating: 3.8, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024302-001', name: '논리적프로그래밍문제해결실습', professor: '강창구',
    credit: 3, rating: 4.1, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024302-002', name: '논리적프로그래밍문제해결실습', professor: '강창구',
    credit: 3, rating: 4.1, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024302-003', name: '논리적프로그래밍문제해결실습', professor: '강창구',
    credit: 3, rating: 4.1, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '목', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024302-004', name: '논리적프로그래밍문제해결실습', professor: '강창구',
    credit: 3, rating: 4.1, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024724-001', name: '자료구조', professor: '김봉기',
    credit: 3, rating: 4.2, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024724-002', name: '자료구조', professor: '김봉기',
    credit: 3, rating: 4.2, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024724-003', name: '자료구조', professor: '최으뜸',
    credit: 3, rating: 4.2, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 2,
    timeSlots: [TimeSlot(day: '월', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11009452-001', name: '컴퓨터과학교육론', professor: '서영건',
    credit: 3, rating: 3.4, difficulty: 2,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '월', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11009473-001', name: '컴퓨터그래픽스', professor: '진효진',
    credit: 3, rating: 3.7, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '월', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11009473-002', name: '컴퓨터그래픽스', professor: '진효진',
    credit: 3, rating: 3.7, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '월', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11009473-003', name: '컴퓨터그래픽스', professor: '진효진',
    credit: 3, rating: 3.7, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024301-001', name: '오토마타와컴파일러', professor: '송진국',
    credit: 3, rating: 3.3, difficulty: 5,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024301-002', name: '오토마타와컴파일러', professor: '송진국',
    credit: 3, rating: 3.3, difficulty: 5,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024301-003', name: '오토마타와컴파일러', professor: '송진국',
    credit: 3, rating: 3.3, difficulty: 5,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '목', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024711-001', name: '소프트웨어공학', professor: '김범수',
    credit: 3, rating: 3.9, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024711-002', name: '소프트웨어공학', professor: '김범수',
    credit: 3, rating: 3.9, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024717-001', name: '백엔드프로그래밍', professor: '김현주',
    credit: 3, rating: 4.4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '월', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024717-002', name: '백엔드프로그래밍', professor: '김현주',
    credit: 3, rating: 4.4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024717-003', name: '백엔드프로그래밍', professor: '손용숙',
    credit: 3, rating: 4.4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024717-004', name: '백엔드프로그래밍', professor: '손용숙',
    credit: 3, rating: 4.4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024722-001', name: '인공지능', professor: '김건우',
    credit: 3, rating: 4.3, difficulty: 4,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024722-002', name: '인공지능', professor: '김건우',
    credit: 3, rating: 4.3, difficulty: 4,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024722-003', name: '인공지능', professor: '김건우',
    credit: 3, rating: 4.3, difficulty: 4,
    hasTeamProject: false, isMajorRequired: false, grade: 3,
    timeSlots: [TimeSlot(day: '목', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024299-001', name: '전공종합설계PBLⅡ', professor: '최상민',
    credit: 3, rating: 4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: true, grade: 4,
    timeSlots: [TimeSlot(day: '화', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024299-002', name: '전공종합설계PBLⅡ', professor: '김건우',
    credit: 3, rating: 4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: true, grade: 4,
    timeSlots: [TimeSlot(day: '목', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11024299-003', name: '전공종합설계PBLⅡ', professor: '강창구',
    credit: 3, rating: 4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: true, grade: 4,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
  Course(
    id: '11024299-004', name: '전공종합설계PBLⅡ', professor: '김지윤',
    credit: 3, rating: 4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: true, grade: 4,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024299-005', name: '전공종합설계PBLⅡ', professor: '윤웅창',
    credit: 3, rating: 4, difficulty: 3,
    hasTeamProject: true, isMajorRequired: true, grade: 4,
    timeSlots: [TimeSlot(day: '수', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11009453-001', name: '컴퓨터과학교재연구', professor: '남영호',
    credit: 3, rating: 3.5, difficulty: 3,
    hasTeamProject: false, isMajorRequired: false, grade: 4,
    timeSlots: [TimeSlot(day: '수', startHour: 16, endHour: 19), TimeSlot(day: '금', startHour: 15, endHour: 18)],
  ),
  Course(
    id: '11009474-001', name: '영상처리', professor: '김민기',
    credit: 3, rating: 3.6, difficulty: 4,
    hasTeamProject: false, isMajorRequired: false, grade: 4,
    timeSlots: [TimeSlot(day: '수', startHour: 9, endHour: 12)],
  ),
  Course(
    id: '11009476-001', name: '모바일프로그래밍', professor: '김지윤',
    credit: 3, rating: 4.5, difficulty: 3,
    hasTeamProject: true, isMajorRequired: false, grade: 4,
    timeSlots: [TimeSlot(day: '목', startHour: 13, endHour: 16)],
  ),
  Course(
    id: '11024716-001', name: '기계학습', professor: '부석준',
    credit: 3, rating: 4.1, difficulty: 4,
    hasTeamProject: false, isMajorRequired: false, grade: 4,
    timeSlots: [TimeSlot(day: '화', startHour: 14, endHour: 17)],
  ),
];
