import '../models/course.dart';

TimeSlot _slot(String day, int startHour, int endHour) =>
    TimeSlot(day: day, startHour: startHour, endHour: endHour);

Course _course({
  required String id,
  required String name,
  required String professor,
  required int credit,
  required double rating,
  required int difficulty,
  required bool hasTeamProject,
  required bool isMajorRequired,
  required int grade,
  required List<TimeSlot> timeSlots,
}) {
  return Course(
    id: id,
    name: name,
    professor: professor,
    credit: credit,
    rating: rating,
    difficulty: difficulty,
    hasTeamProject: hasTeamProject,
    isMajorRequired: isMajorRequired,
    grade: grade,
    timeSlots: timeSlots,
  );
}

final realCourses = [
  _course(
    id: '11024295-001',
    name: '컴퓨터공학을 위한 수학 I',
    professor: '최상미',
    credit: 3,
    rating: 3.2,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: true,
    grade: 1,
    timeSlots: [_slot('화', 13, 16)],
  ),
  _course(
    id: '11024295-002',
    name: '컴퓨터공학을 위한 수학 I',
    professor: '최상미',
    credit: 3,
    rating: 3.2,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: true,
    grade: 1,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11024725-001',
    name: 'C 프로그래밍',
    professor: '김창렬',
    credit: 3,
    rating: 4.0,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 1,
    timeSlots: [_slot('수', 9, 12)],
  ),
  _course(
    id: '11024725-002',
    name: 'C 프로그래밍',
    professor: '김창렬',
    credit: 3,
    rating: 4.0,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 1,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11024725-003',
    name: 'C 프로그래밍',
    professor: '노민재',
    credit: 3,
    rating: 4.0,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 1,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11024725-004',
    name: 'C 프로그래밍',
    professor: '노민재',
    credit: 3,
    rating: 4.0,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 1,
    timeSlots: [_slot('목', 14, 17)],
  ),
  _course(
    id: '11024294-001',
    name: '컴퓨터공학을 위한 수학 II',
    professor: '이수현',
    credit: 3,
    rating: 3.0,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: true,
    grade: 2,
    timeSlots: [_slot('목', 14, 17)],
  ),
  _course(
    id: '11024294-002',
    name: '컴퓨터공학을 위한 수학 II',
    professor: '이수현',
    credit: 3,
    rating: 3.0,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: true,
    grade: 2,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11009499-001',
    name: '컴퓨터시스템개론',
    professor: '이로빈',
    credit: 3,
    rating: 3.5,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('화', 14, 17)],
  ),
  _course(
    id: '11009499-002',
    name: '컴퓨터시스템개론',
    professor: '이로빈',
    credit: 3,
    rating: 3.5,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11009499-003',
    name: '컴퓨터시스템개론',
    professor: '이로빈',
    credit: 3,
    rating: 3.5,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('금', 9, 12)],
  ),
  _course(
    id: '11024300-001',
    name: 'C++ 프로그래밍',
    professor: '김유성',
    credit: 3,
    rating: 3.8,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('월', 9, 12)],
  ),
  _course(
    id: '11024300-002',
    name: 'C++ 프로그래밍',
    professor: '김유성',
    credit: 3,
    rating: 3.8,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('월', 14, 17)],
  ),
  _course(
    id: '11024300-003',
    name: 'C++ 프로그래밍',
    professor: '김유성',
    credit: 3,
    rating: 3.8,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('금', 9, 12)],
  ),
  _course(
    id: '11024300-004',
    name: 'C++ 프로그래밍',
    professor: '이수민',
    credit: 3,
    rating: 3.8,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('금', 13, 16)],
  ),
  _course(
    id: '11024302-001',
    name: '알고리즘 문제해결 실습',
    professor: '강태규',
    credit: 3,
    rating: 4.1,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('월', 9, 12)],
  ),
  _course(
    id: '11024302-002',
    name: '알고리즘 문제해결 실습',
    professor: '강태규',
    credit: 3,
    rating: 4.1,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('월', 13, 16)],
  ),
  _course(
    id: '11024302-003',
    name: '알고리즘 문제해결 실습',
    professor: '강태규',
    credit: 3,
    rating: 4.1,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('목', 14, 17)],
  ),
  _course(
    id: '11024302-004',
    name: '알고리즘 문제해결 실습',
    professor: '강태규',
    credit: 3,
    rating: 4.1,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11024724-001',
    name: '자료구조',
    professor: '김현기',
    credit: 3,
    rating: 4.2,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11024724-002',
    name: '자료구조',
    professor: '김현기',
    credit: 3,
    rating: 4.2,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('수', 9, 12)],
  ),
  _course(
    id: '11024724-003',
    name: '자료구조',
    professor: '최은우',
    credit: 3,
    rating: 4.2,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 2,
    timeSlots: [_slot('금', 14, 17)],
  ),
  _course(
    id: '11009452-001',
    name: '컴퓨터과학개론',
    professor: '신영건',
    credit: 3,
    rating: 3.4,
    difficulty: 2,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11009473-001',
    name: '컴퓨터그래픽스',
    professor: '진효진',
    credit: 3,
    rating: 3.7,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11009473-002',
    name: '컴퓨터그래픽스',
    professor: '진효진',
    credit: 3,
    rating: 3.7,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('화', 13, 16)],
  ),
  _course(
    id: '11009473-003',
    name: '컴퓨터그래픽스',
    professor: '진효진',
    credit: 3,
    rating: 3.7,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11024301-001',
    name: '오토마타와 컴파일러',
    professor: '윤진구',
    credit: 3,
    rating: 3.3,
    difficulty: 5,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11024301-002',
    name: '오토마타와 컴파일러',
    professor: '윤진구',
    credit: 3,
    rating: 3.3,
    difficulty: 5,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('금', 13, 16)],
  ),
  _course(
    id: '11024301-003',
    name: '오토마타와 컴파일러',
    professor: '윤진구',
    credit: 3,
    rating: 3.3,
    difficulty: 5,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('목', 13, 16)],
  ),
  _course(
    id: '11024711-001',
    name: '소프트웨어공학',
    professor: '김범수',
    credit: 3,
    rating: 3.9,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('월', 9, 12)],
  ),
  _course(
    id: '11024711-002',
    name: '소프트웨어공학',
    professor: '김범수',
    credit: 3,
    rating: 3.9,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('월', 14, 17)],
  ),
  _course(
    id: '11024717-001',
    name: '백엔드 웹 프로그래밍',
    professor: '김민주',
    credit: 3,
    rating: 4.4,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11024717-002',
    name: '백엔드 웹 프로그래밍',
    professor: '김민주',
    credit: 3,
    rating: 4.4,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('수', 9, 12)],
  ),
  _course(
    id: '11024717-003',
    name: '백엔드 웹 프로그래밍',
    professor: '오재용',
    credit: 3,
    rating: 4.4,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('금', 9, 12)],
  ),
  _course(
    id: '11024717-004',
    name: '백엔드 웹 프로그래밍',
    professor: '오재용',
    credit: 3,
    rating: 4.4,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11024722-001',
    name: '인공지능',
    professor: '김건우',
    credit: 3,
    rating: 4.3,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11024722-002',
    name: '인공지능',
    professor: '김건우',
    credit: 3,
    rating: 4.3,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('화', 13, 16)],
  ),
  _course(
    id: '11024722-003',
    name: '인공지능',
    professor: '김건우',
    credit: 3,
    rating: 4.3,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 3,
    timeSlots: [_slot('목', 13, 16)],
  ),
  _course(
    id: '11024299-001',
    name: '전공종합설계 PBL',
    professor: '최상미',
    credit: 3,
    rating: 4.0,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: true,
    grade: 4,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11024299-002',
    name: '전공종합설계 PBL',
    professor: '김건우',
    credit: 3,
    rating: 4.0,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: true,
    grade: 4,
    timeSlots: [_slot('목', 9, 12)],
  ),
  _course(
    id: '11024299-003',
    name: '전공종합설계 PBL',
    professor: '강태규',
    credit: 3,
    rating: 4.0,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: true,
    grade: 4,
    timeSlots: [_slot('수', 14, 17)],
  ),
  _course(
    id: '11024299-004',
    name: '전공종합설계 PBL',
    professor: '김지윤',
    credit: 3,
    rating: 4.0,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: true,
    grade: 4,
    timeSlots: [_slot('금', 13, 16)],
  ),
  _course(
    id: '11024299-005',
    name: '전공종합설계 PBL',
    professor: '노민재',
    credit: 3,
    rating: 4.0,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: true,
    grade: 4,
    timeSlots: [_slot('월', 13, 16)],
  ),
  _course(
    id: '11009453-001',
    name: '컴퓨터과학특별연구',
    professor: '임영택',
    credit: 3,
    rating: 3.5,
    difficulty: 3,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 4,
    timeSlots: [_slot('수', 16, 19), _slot('금', 15, 18)],
  ),
  _course(
    id: '11009474-001',
    name: '영상처리',
    professor: '김미경',
    credit: 3,
    rating: 3.6,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 4,
    timeSlots: [_slot('화', 9, 12)],
  ),
  _course(
    id: '11009476-001',
    name: '모바일프로그래밍',
    professor: '김지윤',
    credit: 3,
    rating: 4.5,
    difficulty: 3,
    hasTeamProject: true,
    isMajorRequired: false,
    grade: 4,
    timeSlots: [_slot('목', 13, 16)],
  ),
  _course(
    id: '11024716-001',
    name: '기계학습',
    professor: '부태용',
    credit: 3,
    rating: 4.1,
    difficulty: 4,
    hasTeamProject: false,
    isMajorRequired: false,
    grade: 4,
    timeSlots: [_slot('수', 14, 17)],
  ),
];
